'use client';

import { useState } from 'react';
import { Star, Award, Zap, TrendingUp, ChevronRight, CheckCircle2, UserCircle, Briefcase } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';

export default function Recommendations() {
  const [userType, setUserType] = useState<'Business' | 'Personal'>('Business');
  const [appliedStrategies, setAppliedStrategies] = useState<string[]>([]);

  const strategies = [
    {
      id: 'dynamic-comp',
      title: 'Dynamic Compensation Matrix',
      description: 'Shift from flat-rate vouchers to dynamic compensation based on passenger lifetime value and current delay severity.',
      impact: 'High',
      effort: 'Medium',
      improvement: '+18% Satisfaction',
      icon: <Zap className="w-6 h-6 text-primary" />,
      for: ['Business', 'Personal']
    },
    {
      id: 'predictive-maint',
      title: 'Predictive Maintenance Routing',
      description: 'Reroute aircraft showing early warning signs of mechanical issues to hubs with specialized maintenance crews before failure occurs.',
      impact: 'Very High',
      effort: 'High',
      improvement: '-35% Delay Frequency',
      icon: <TrendingUp className="w-6 h-6 text-tertiary" />,
      for: ['Business', 'Personal']
    },
    {
      id: 'micro-moments',
      title: 'Micro-Moments of Delight',
      description: 'Empower gate agents with a $50 discretionary budget per flight to resolve minor frictions instantly without manager approval.',
      impact: 'Medium',
      effort: 'Low',
      improvement: '+12% NPS',
      icon: <Star className="w-6 h-6 text-primary" />,
      for: ['Personal']
    },
    {
      id: 'priority-rebooking',
      title: 'AI-Driven Priority Rebooking',
      description: 'Automatically rebook high-value business travelers on the next available flight (even on competitors) during major disruptions.',
      impact: 'High',
      effort: 'Low',
      improvement: '+22% Retention',
      icon: <Briefcase className="w-6 h-6 text-primary" />,
      for: ['Business']
    }
  ];

  const filteredStrategies = strategies.filter(s => s.for.includes(userType));

  const handleApply = (id: string) => {
    if (appliedStrategies.includes(id)) return;
    setAppliedStrategies(prev => [...prev, id]);
  };

  const [expandedId, setExpandedId] = useState<string | null>(null);

  const getReasoning = (id: string) => {
    const reasonings: Record<string, { what: string; why: string; next: string }> = {
      'dynamic-comp': {
        what: 'Standard vouchers are being replaced by a dynamic system.',
        why: 'Flat-rate compensation fails to account for passenger value and the actual severity of the delay.',
        next: 'Deploy the matrix to gate agents and monitor NPS impact over the next 30 days.'
      },
      'predictive-maint': {
        what: 'Aircraft are being proactively rerouted based on sensor data.',
        why: 'Preventing a delay at the hub is 4x cheaper than managing a mid-journey mechanical failure.',
        next: 'Integrate the maintenance schedule with the flight operations dashboard.'
      },
      'micro-moments': {
        what: 'Gate agents are receiving discretionary budgets.',
        why: 'Small, immediate resolutions prevent minor frustrations from escalating into negative social sentiment.',
        next: 'Train agents on the "delight threshold" and track usage patterns.'
      },
      'priority-rebooking': {
        what: 'High-value travelers are automatically rebooked during disruptions.',
        why: 'Business travelers prioritize schedule integrity above all else; competitor rebooking builds long-term loyalty.',
        next: 'Enable automated competitor API integration for real-time seat availability.'
      }
    };
    return reasonings[id];
  };

  return (
    <main className="flex-grow px-6 lg:px-12 max-w-7xl mx-auto w-full pb-20">
      <div className="flex flex-col md:flex-row md:items-end justify-between mb-12 mt-8 gap-6">
        <div>
          <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight text-on-surface mb-4 font-headline">
            Smart Recommendations
          </h1>
          <p className="text-on-surface-variant max-w-2xl text-lg">
            Actionable strategies generated by our AI engine to optimize passenger experience and operational efficiency.
          </p>
        </div>
        
        <div className="flex bg-surface-container-low p-1.5 rounded-2xl border border-outline-variant/10 self-start md:self-auto">
          <button 
            onClick={() => setUserType('Business')}
            className={`flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-bold transition-all ${userType === 'Business' ? 'bg-primary text-white shadow-md shadow-primary/20' : 'text-on-surface-variant hover:bg-surface-container'}`}
          >
            <Briefcase className="w-4 h-4" /> Business
          </button>
          <button 
            onClick={() => setUserType('Personal')}
            className={`flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-bold transition-all ${userType === 'Personal' ? 'bg-primary text-white shadow-md shadow-primary/20' : 'text-on-surface-variant hover:bg-surface-container'}`}
          >
            <UserCircle className="w-4 h-4" /> Personal
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Main Strategies */}
        <div className="lg:col-span-8 space-y-6">
          <h2 className="text-xl font-bold font-headline text-on-surface mb-6 flex items-center gap-2">
            <Award className="w-5 h-5 text-primary" /> Top Priority Interventions for {userType}
          </h2>
          
          <AnimatePresence mode="popLayout">
            {filteredStrategies.map((strategy, index) => (
              <motion.div 
                key={strategy.id}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, scale: 0.95 }}
                transition={{ delay: index * 0.1 }}
                className="glass-panel p-6 md:p-8 rounded-3xl group hover:border-primary/30 transition-colors relative overflow-hidden"
              >
                <div className="flex flex-col md:flex-row gap-6 items-start">
                  <div className="w-14 h-14 rounded-2xl bg-surface-container-low flex items-center justify-center shrink-0 group-hover:bg-primary/10 transition-colors">
                    {strategy.icon}
                  </div>
                  <div className="flex-grow">
                    <div className="flex items-center gap-3 mb-2">
                      <h3 className="text-xl font-bold font-headline text-on-surface">{strategy.title}</h3>
                      <span className="text-[10px] font-bold px-2 py-0.5 bg-tertiary/10 text-tertiary rounded-full uppercase tracking-widest">
                        {strategy.improvement}
                      </span>
                    </div>
                    <p className="text-on-surface-variant leading-relaxed mb-4">
                      {strategy.description}
                    </p>

                    {/* Expandable Reasoning */}
                    <div className="mb-6">
                      <button 
                        onClick={() => setExpandedId(expandedId === strategy.id ? null : strategy.id)}
                        className="text-xs font-bold text-primary flex items-center gap-1 hover:underline transition-all"
                      >
                        {expandedId === strategy.id ? 'Hide reasoning' : 'Why this recommendation?'}
                        <ChevronRight className={`w-3 h-3 transition-transform ${expandedId === strategy.id ? 'rotate-90' : ''}`} />
                      </button>
                      
                      <AnimatePresence>
                        {expandedId === strategy.id && (
                          <motion.div 
                            initial={{ opacity: 0, height: 0 }}
                            animate={{ opacity: 1, height: 'auto' }}
                            exit={{ opacity: 0, height: 0 }}
                            className="overflow-hidden"
                          >
                            <div className="mt-4 p-4 bg-surface-container-low/50 rounded-2xl border border-outline-variant/10 space-y-3">
                              <div>
                                <span className="text-[10px] font-bold text-on-surface-variant uppercase tracking-widest block mb-1">What is happening</span>
                                <p className="text-xs text-on-surface leading-relaxed">{getReasoning(strategy.id).what}</p>
                              </div>
                              <div>
                                <span className="text-[10px] font-bold text-on-surface-variant uppercase tracking-widest block mb-1">Why it is happening</span>
                                <p className="text-xs text-on-surface leading-relaxed">{getReasoning(strategy.id).why}</p>
                              </div>
                              <div>
                                <span className="text-[10px] font-bold text-primary uppercase tracking-widest block mb-1">What to do next</span>
                                <p className="text-xs text-on-surface font-semibold leading-relaxed">{getReasoning(strategy.id).next}</p>
                              </div>
                            </div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>

                    <div className="flex flex-wrap gap-4 items-center">
                      <span className="text-xs font-bold px-3 py-1 bg-surface-container-low rounded-lg text-on-surface">
                        Impact: <span className={strategy.impact.includes('High') ? 'text-primary' : ''}>{strategy.impact}</span>
                      </span>
                      <span className="text-xs font-bold px-3 py-1 bg-surface-container-low rounded-lg text-on-surface">
                        Effort: {strategy.effort}
                      </span>
                      
                      <button 
                        onClick={() => handleApply(strategy.id)}
                        disabled={appliedStrategies.includes(strategy.id)}
                        className={`ml-auto flex items-center gap-2 px-6 py-2.5 rounded-xl text-sm font-bold transition-all ${
                          appliedStrategies.includes(strategy.id)
                            ? 'bg-tertiary/10 text-tertiary cursor-default'
                            : 'bg-primary text-white hover:bg-primary-dark shadow-lg shadow-primary/20 active:scale-[0.98]'
                        }`}
                      >
                        {appliedStrategies.includes(strategy.id) ? (
                          <>
                            <CheckCircle2 className="w-4 h-4" /> Strategy Applied
                          </>
                        ) : (
                          <>
                            Apply Strategy <ChevronRight className="w-4 h-4" />
                          </>
                        )}
                      </button>
                    </div>
                  </div>
                </div>
              </motion.div>
            ))}
          </AnimatePresence>
        </div>

        {/* Sidebar */}
        <div className="lg:col-span-4 space-y-6">
          <div className="glass-elevated p-8 rounded-3xl bg-primary text-white relative overflow-hidden">
            <div className="absolute top-0 right-0 w-32 h-32 bg-white/10 rounded-full blur-2xl -mr-10 -mt-10"></div>
            <h3 className="text-xl font-bold font-headline mb-4 relative z-10">Generate Custom Plan</h3>
            <p className="text-primary-container text-sm leading-relaxed mb-6 relative z-10">
              Need strategies tailored to a specific route or demographic? Let our engine build a custom playbook.
            </p>
            <button className="w-full bg-white text-primary font-bold py-3 rounded-xl hover:bg-surface-container-lowest transition-colors relative z-10">
              Start Wizard
            </button>
          </div>

          <div className="glass-panel p-6 rounded-3xl">
            <h3 className="font-bold font-headline text-on-surface mb-4">Implementation Success</h3>
            <div className="space-y-4">
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 rounded-full border-4 border-primary flex items-center justify-center font-bold text-sm text-primary">
                  84%
                </div>
                <div>
                  <div className="font-bold text-sm text-on-surface">Dynamic Comp</div>
                  <div className="text-xs text-on-surface-variant">Adoption rate</div>
                </div>
              </div>
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 rounded-full border-4 border-tertiary flex items-center justify-center font-bold text-sm text-tertiary">
                  62%
                </div>
                <div>
                  <div className="font-bold text-sm text-on-surface">Micro-Moments</div>
                  <div className="text-xs text-on-surface-variant">Adoption rate</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}
